/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package debug;

import java.awt.event.KeyEvent;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import machine.I8085;
import machine.Memory;

/**
 *
 * @author Administrator
 */
public class Debugger extends javax.swing.JDialog {

    private I8085 cpu;
    private Memory m;
    private OpcodeTable t;
    
    private boolean step;
    private boolean tilRet;
    
    /**
     * Creates new form Debugger
     */
    public Debugger(I8085 proc, Memory mem) {
        cpu = proc;
        m = mem;        
        t = new OpcodeTable();
        initComponents();
    }
    
    public void Debug(int addr, int opcode) {
        step = false;
        
        printRegTable(regs, 0, 1, true, cpu.getRegA());
        printRegTable(regs, 1, 1, true, cpu.getFlags());
        printRegTable(regs, 2, 1, true, cpu.getRegB());
        printRegTable(regs, 3, 1, true, cpu.getRegC());
        printRegTable(regs, 4, 1, true, cpu.getRegD());
        printRegTable(regs, 5, 1, true, cpu.getRegE());
        printRegTable(regs, 6, 1, true, cpu.getRegH());
        printRegTable(regs, 7, 1, true, cpu.getRegL());
        
        regPC.setText(String.format("%04X", cpu.getRegPC()));
        regSP.setText(String.format("%04X", cpu.getRegSP()));
        
        printRegTable(flags, 0, 0, false, cpu.getFlags());
        printRegTable(sim, 0, 0, false, cpu.getRegSim());
        
        printDisassembly(addr);
        
        if (tilRet) {
            if (opcode != 0xc9) {
                step = true;
            }
            else {
                tilRet = false;
            }
        }
        while (!step) {
            
        }
    }

    private void printRegTable(JTable tab, int r, int c, boolean hex, int val) {
        int cc = c;
        int vv = val;
        TableModel tm = tab.getModel();
        
        if (hex) {
            tm.setValueAt(String.format("%02X", vv), r, cc);
            cc++;
        }
        
        for(int n=0; n<8; n++) {
            tm.setValueAt((vv & 0x80) !=0 ? "1" : "0", r, cc);
            vv <<= 1;
            cc++;
        }
    }
    
    private void printDisassembly(int from) {
        int a = from;
        int l = dis.getRowCount();
        String s,s1,s2;
        String h;
        
        TableModel tm = dis.getModel();
        
        for(int n=0; n<l; n++) {
            tm.setValueAt(String.format("%04X", a), n, 0);
            h = String.format("%02x",m.readByte(a));
            s = t.getOpcode(h);
            a++;
            s1 = t.getOp1(h);
            s2 = t.getOp2(h);
            
            if (s1!=null) {
                if (s1.equals("xx")) {
                    s1 = String.format("%02X",m.readByte(a));
                    a++;
                }
                if (s1.equals("xxxx")) {
                    s1 = String.format("%02X",m.readByte(a));
                    a++;
                    s1 = String.format("%02X",m.readByte(a)) + s1;
                    a++;
                }
                s = s + " " + s1;
            }

            if (s2!=null) {
                if (s2.equals("xx")) {
                    s2 = String.format("%02X",m.readByte(a));
                    a++;
                }
                if (s2.equals("xxxx")) {
                    s2 = String.format("%02X",m.readByte(a));
                    a++;
                    s2 = String.format("%02X",m.readByte(a)) + s2;
                    a++;
                }
                s = s + "," + s2;
            }

            tm.setValueAt(s, n, 1);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        regPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        regs = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        flags = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        sim = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        regPC = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        regSP = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        dis = new javax.swing.JTable();
        ButtonStep = new javax.swing.JButton();
        ButtonRet = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Debugger");
        setResizable(false);

        regPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Registers"));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        regs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        regs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A", "00", null, null, null, null, null, null, null, null},
                {"F", "00", null, null, null, null, null, null, null, null},
                {"B", "00", null, null, null, null, null, null, null, null},
                {"C", "00", null, null, null, null, null, null, null, null},
                {"D", "00", null, null, null, null, null, null, null, null},
                {"E", "00", null, null, null, null, null, null, null, null},
                {"H", "00", null, null, null, null, null, null, null, null},
                {"L", "00", null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "hex", "7", "6", "5", "4", "3", "2", "1", "0"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        regs.setAutoscrolls(false);
        regs.setFocusable(false);
        regs.setRowSelectionAllowed(false);
        regs.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(regs);
        regs.getColumnModel().getColumn(0).setResizable(false);
        regs.getColumnModel().getColumn(0).setPreferredWidth(20);
        regs.getColumnModel().getColumn(1).setResizable(false);
        regs.getColumnModel().getColumn(1).setPreferredWidth(50);
        regs.getColumnModel().getColumn(2).setResizable(false);
        regs.getColumnModel().getColumn(2).setPreferredWidth(20);
        regs.getColumnModel().getColumn(3).setResizable(false);
        regs.getColumnModel().getColumn(3).setPreferredWidth(20);
        regs.getColumnModel().getColumn(4).setResizable(false);
        regs.getColumnModel().getColumn(4).setPreferredWidth(20);
        regs.getColumnModel().getColumn(5).setResizable(false);
        regs.getColumnModel().getColumn(5).setPreferredWidth(20);
        regs.getColumnModel().getColumn(6).setResizable(false);
        regs.getColumnModel().getColumn(6).setPreferredWidth(20);
        regs.getColumnModel().getColumn(7).setResizable(false);
        regs.getColumnModel().getColumn(7).setPreferredWidth(20);
        regs.getColumnModel().getColumn(8).setResizable(false);
        regs.getColumnModel().getColumn(8).setPreferredWidth(20);
        regs.getColumnModel().getColumn(9).setResizable(false);
        regs.getColumnModel().getColumn(9).setPreferredWidth(20);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        flags.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        flags.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", "0", "0", "0", "0", "0", "0", "0"}
            },
            new String [] {
                "S", "Z", "U", "A", "*", "P", "V", "C"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        flags.setAutoscrolls(false);
        flags.setFocusable(false);
        flags.setRowSelectionAllowed(false);
        flags.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(flags);
        flags.getColumnModel().getColumn(0).setResizable(false);
        flags.getColumnModel().getColumn(0).setPreferredWidth(20);
        flags.getColumnModel().getColumn(1).setResizable(false);
        flags.getColumnModel().getColumn(1).setPreferredWidth(20);
        flags.getColumnModel().getColumn(2).setResizable(false);
        flags.getColumnModel().getColumn(2).setPreferredWidth(20);
        flags.getColumnModel().getColumn(3).setResizable(false);
        flags.getColumnModel().getColumn(3).setPreferredWidth(20);
        flags.getColumnModel().getColumn(4).setResizable(false);
        flags.getColumnModel().getColumn(4).setPreferredWidth(20);
        flags.getColumnModel().getColumn(5).setResizable(false);
        flags.getColumnModel().getColumn(5).setPreferredWidth(20);
        flags.getColumnModel().getColumn(6).setResizable(false);
        flags.getColumnModel().getColumn(6).setPreferredWidth(20);
        flags.getColumnModel().getColumn(7).setResizable(false);
        flags.getColumnModel().getColumn(7).setPreferredWidth(20);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        sim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", "0", "0", "0", "0", "0", "0", "0"}
            },
            new String [] {
                "SO", "I7", "I6", "I5", "IE", "M7", "M6", "M5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sim.setAutoscrolls(false);
        sim.setFocusable(false);
        sim.setRowSelectionAllowed(false);
        sim.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(sim);
        sim.getColumnModel().getColumn(0).setResizable(false);
        sim.getColumnModel().getColumn(0).setPreferredWidth(20);
        sim.getColumnModel().getColumn(1).setResizable(false);
        sim.getColumnModel().getColumn(1).setPreferredWidth(20);
        sim.getColumnModel().getColumn(2).setResizable(false);
        sim.getColumnModel().getColumn(2).setPreferredWidth(20);
        sim.getColumnModel().getColumn(3).setResizable(false);
        sim.getColumnModel().getColumn(3).setPreferredWidth(20);
        sim.getColumnModel().getColumn(4).setResizable(false);
        sim.getColumnModel().getColumn(4).setPreferredWidth(20);
        sim.getColumnModel().getColumn(5).setResizable(false);
        sim.getColumnModel().getColumn(5).setPreferredWidth(20);
        sim.getColumnModel().getColumn(6).setResizable(false);
        sim.getColumnModel().getColumn(6).setPreferredWidth(20);
        sim.getColumnModel().getColumn(7).setResizable(false);
        sim.getColumnModel().getColumn(7).setPreferredWidth(20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PC: ");

        regPC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        regPC.setText("0000");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("SP: ");

        regSP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        regSP.setText("0000");

        javax.swing.GroupLayout regPanelLayout = new javax.swing.GroupLayout(regPanel);
        regPanel.setLayout(regPanelLayout);
        regPanelLayout.setHorizontalGroup(
            regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(regPanelLayout.createSequentialGroup()
                        .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(regPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(regSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(regPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(regPC, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        regPanelLayout.setVerticalGroup(
            regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(regPC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regSP)
                            .addComponent(jLabel2))
                        .addContainerGap())
                    .addGroup(regPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Disassembly"));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setFocusable(false);

        dis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Address", "Instruction"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dis.setFocusable(false);
        dis.setRowSelectionAllowed(false);
        dis.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(dis);
        dis.getColumnModel().getColumn(0).setResizable(false);
        dis.getColumnModel().getColumn(0).setPreferredWidth(20);
        dis.getColumnModel().getColumn(1).setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        ButtonStep.setMnemonic(KeyEvent.VK_S);
        ButtonStep.setText("Step");
        ButtonStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStepActionPerformed(evt);
            }
        });

        ButtonRet.setMnemonic(KeyEvent.VK_R);
        ButtonRet.setText("Go until ret");
        ButtonRet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButtonRet)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonStep)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(regPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonStep)
                    .addComponent(ButtonRet))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStepActionPerformed
        step = true;
        tilRet = false;
    }//GEN-LAST:event_ButtonStepActionPerformed

    private void ButtonRetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRetActionPerformed
        tilRet = true;
        step = true;
    }//GEN-LAST:event_ButtonRetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRet;
    private javax.swing.JButton ButtonStep;
    private javax.swing.JTable dis;
    private javax.swing.JTable flags;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel regPC;
    private javax.swing.JPanel regPanel;
    private javax.swing.JLabel regSP;
    private javax.swing.JTable regs;
    private javax.swing.JTable sim;
    // End of variables declaration//GEN-END:variables
}
